### ISSUE TITLE
Ingest text data via Dataset.Text

### ISSUE THREAD

**Issue by aiqc** [aiqc/aiqc#13]
> Difficulty: ★★☆☆☆

## Background
AIQC has datasets of multiple types. 

As an example, `Dataset.Tabular` consists of a single `File.Tabular`. Here, the file contains both features and labels. 

Alternatively, the `Dataset.Image` consists of many `Files.Image` because images aren't easily structured in a Parquet file. 

## Problem
There is no way to ingest `txt` files or strings for NLP.

## Solution
Since strings can be easily incorporated into tabular parquet files with dtype protection, and we already have a lot of ways for working with tabular data -- let's attempt to start by ingesting many strings into a single `File.Tabular`. Where each string sample is just a row in the dataframe.

So the `Dataset.Text` class would have the creation methods: `from_strings(strings:list)`,  `from_folder()`, `from_pandas()`: 
- Construct a pandas dataframe with a specific column `txt` from the strings. This column could be a default input for by preprocessing and read methods?
- Create a `File.Tabular` from that dataframe.

^ In order to accomplish the above bullets, you could even use the Tabular methods `Dataset.Tabular.from_pandas()` and `Dataset.Image.from_folder()` to make this easy.

## Discussion
Should the final `dataset_type='text'`, so that preprocessing and other downstream methods know how to handle it?

**Comment by sahilgupta2105** [comment]
Although the current implementation for Text Dataset can be subsumed in the Tabular class, I think having a separate dataset type for text will give us more flexibility in future.
