### ISSUE TITLE
Extract Dataset.Text strings to numpy

### ISSUE THREAD

**Issue by aiqc** [aiqc/AIQC#14]
> Difficulty: ★★☆☆☆

## Background
`Dataset.Tabular` and `Dataset.Image` both have the methods `to_numpy()` and `to_pandas()`. 

`Dataset.Image` is read into memory using the Pillow library. Images can also be read either `to_pillow()` or `to_numpy()`. `Dataset.Image` disallows the creation of an `Encoderset` because it will use transforms/augmentation eventually.

NLP encodes either at the word "Bag of words" or character level. 

## Problem
We don't have a way to prepare raw text data as an array for a neural network. 

## Solution
- `to_numpy()` method that uses `sklearn.feature_extraction.text` methods like [`CountVectorizer ` and `TfidfVectorizer()`](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfTransformer.html#sklearn.feature_extraction.text.TfidfTransformer)
- `frequency:bool=True` argument in case they just want to return the counts.

## Discussion
- Alternatively, SpaCy has a Vocab object and seems much more language aware. However, it also seems a lot more involved, so I thought that this would be an easy way to get started.

**Comment by aiqc** [comment]
Alternatively, SpaCy has a Vocab class.

**Comment by sahilgupta2105** [comment]
@aiqc this issue sounds like pre-processing the text data in form of numbers using different strategies like bag of words, inverse freq ... this probably makes sense in the to_numpy() method for the Text dataset, right? I am looking at the schema and the documentation, and it seems like Featureset would be excepting pre-processed data

**Comment by aiqc** [comment]
@sahilgupta2105 Agreed, providing 1 or 2 of these options of `Dataset.Text.to_numpy()` would be the best a good way to get started.

If we find that we need more structure around many sequential text preprocessing steps, then in the future we may need to look into something like `Featurecoder.Text`.
