### ISSUE TITLE
Create Dataset.Sequence

### ISSUE THREAD

**Issue by aiqc** [aiqc/AIQC#19]
> Difficulty: ★★☆☆☆ 
(verifying the metadata across files could take a bit of work)

## Background
* `Dataset.Tabular` is intended for single-File tabular data that preserves dtypes. It uses the `File.Tabular` class to create its files. 
* There is already an example of how to create multi-File datasets in `Dataset.Image` with a `.from_folder()` method. This method verifies that all `File.Image` have the same dimensions.

## Problem
There is currently no way to ingest multi-file tabular datasets like time series data.

## Solution
- A `Dataset.Sequence.from_folder()` method. 
- A `Dataset.Sequence.from_numpy()` method for 3D ndarrays. Verify that they are 3D. Verify that they are ndarray and reject _structured arrays._
- Skip *from_pandas* for now unless you think that panel data or a list of 2d dataframes are important ways of ingesting time series data.
- Similar to how `Dataset.Image` creates multiple files and verifies their dimensions, `Dataset.Sequence` should verify the number of columns and rows.
- If ingesting Files, verify that the column names and the order of the column names are the same in all files. If not, then reject the entire dataset.
- Verify the number of columns and rows. Reject the entire dataset if the columns of any file are not the same. 

## Discussion
- Is "Sequence" a good name?
- Are xarray and hdfs popular enough that we should have methods for these formats?
- If a file has less rows than another file, then should we offer to fill-in/ pad the missing values with a user-defined value? It would be tricky to get the timestamp column correct? So it may be better to reject it? What do you think?

**Comment by hydrogeohc** [comment]
# Is "Sequence" a good name? It is so far. 
# Are xarray and hdfs popular enough that we should have methods for these formats? I think these two files are popular at scientific fields.
