### ISSUE TITLE
Handle KeyboardInterrupt of Batch.run_jobs() gracefully 

### ISSUE THREAD

**Issue by aiqc** [aiqc/aiqc#24]
> Difficulty: ★★☆☆☆

## Background
The only way to interrupt the `Batch.run_jobs()` loop when it is running on the main process is the interrupt it:
* Python shell <kbd>ctrl</kbd>+<kbd>c</kbd>
* Jupyter <kbd>i</kbd>+<kbd>i</kbd>

It is possible to use Python to intercept the keyboard interrupt in order to handle this gracefully.
https://stackoverflow.com/a/4205386/5739514

## Problem
Despite the fact that the AIQC backend knows how to handle an interrupted queue of jobs, the interrupt spits out a whole page of traceback. If I was new to AIQC, I feel like this would cause me to be worried about the integrity of my data.

![image](https://user-images.githubusercontent.com/74990642/112631935-e4d7d080-8e0d-11eb-9755-60fb47d52ba7.png)

## Solution
Intercept the command and print a message to the user like "Queue was gracefully interrupted."

**Comment by aiqc** [comment]
🎉 Solved by @amoh-godwin ~ Thank you!

**Comment by aiqc** [comment]
Actually, it's not killing the loop, it's just acknowledging the KeyboardInterrupt and printing the message

**Comment by aiqc** [comment]
had to put the entire for loop inside the try statement. Previously it was inside the for loop acting on a single iteration

**Comment by amoh-godwin** [comment]
@aiqc Thank you so much for accepting my commit and fixing the errors with it. Just learnt something new.
